# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32912c131a0e5b79b88d0696d811ce25eeee40ec14c82f1708a28e0aca99e4b57574026e4917632e65af121901d5cabb08d777e260be43fc7c8b4f9cf3f92693

test:
  secret_key_base: ff4726b221db6ac1a208d0491d6a4cc3778fad48928af34afb57128b75d7571f3ae3bad379f0b64e3245d5a353c549e6412c01b8932b8375ea6b50ab249724e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
